### ISSUE TITLE
Cannot find module `chai`

### ISSUE THREAD

**Issue by b264** [angular-actioncable/angular-actioncable#15]
While using the development environment instructions

```module.js:341
    throw err;
    ^
​
Error: Cannot find module 'chai'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/.../code/angular-actioncable/gulpfile.js:2:12)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)```

**Comment by razorcd** [comment]
Which command throws this error ?

**Comment by b264** [comment]
@ZempTime Are you able to reproduce this?

**Comment by b264** [comment]
`npm` now runs the tests; this may not be an issue

**Comment by b264** [comment]
This would only affect contribution & development.  Closing as not an end-user issue.
